### ISSUE TITLE
Example in the readme is not working

### ISSUE THREAD

**Issue by cyd3r** [amosbastian/understat#3]
The example in the readme is not updated and still uses the `get_players` method which is not available anymore in the master branch.

Steps to reproduce:
- `pip install understat`
- run the example

I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "test.py", line 12, in main
    data = await understat.get_players("epl", 2019, {"team_title": "Manchester United"})
AttributeError: 'Understat' object has no attribute 'get_players'
```

Works fine with version 0.1.0 though

**Comment by amosbastian** [comment]
Fixed the example, thanks!
